### ISSUE TITLE
Node version is outdated

### ISSUE THREAD

**Issue by pokemonspeler** [orgoro/coverage#208]
during the usage of thes action github publishes the following warning
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: orgoro/coverage@v3
```

**Comment by orgoro** [comment]
Thanks @pokemonspeler I will update

**Comment by pokemonspeler** [comment]
👍

**Comment by RobertDeRose** [comment]
@orgoro You want a PR for this?

**Comment by m4rtinpf** [comment]
I see that a [PR](https://github.com/orgoro/coverage/pull/243) was merged to update Node from 12 to 16, but I'm still getting the warning:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: orgoro/coverage@v3. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

My (abridged) workflow YAML:

```
name: PR check

on: [ pull_request ]

jobs:
...
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
...
    steps:
...
      - name: Code coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: .8
```

@orgoro
