### ISSUE TITLE
Confusing (outdated?) documentation (--cov flag)

### ISSUE THREAD

**Issue by drernie** [orgoro/coverage#241]
> You can create a coverage report using python:

> pytest $ pytest --cov-report xml:path/to/coverage.xml
> coverage $ coverage xml path/to/coverage.xml

First of all, it wasn't clear to me whether I needed BOTH of those, or just one.

Secondly, the given pytest command did not work for me. I had to add '--cov':

`poetry run pytest --cov --cov-report xml:coverage.xml`

Can you clarify?

**Comment by drernie** [comment]
I personally would have found it incredibly helpful to have a complete example like this (assuming it is correct)
```
    - name: Test with pytest
      run: |
        poetry run pytest --cov --cov-report xml:coverage.xml
    - name: Get Coverage Report
      uses: orgoro/coverage@v3
      with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
 ```
 
 But thanks for making this Action, it is awesome!
