### ISSUE TITLE
Working directory setting not respected

### ISSUE THREAD

**Issue by caire-bear** [orgoro/coverage#246]
We have a monorepo and run coverage in each service. The working directory setting in defaults isn't used and requires prepending the working directory path to the coverage file.

You can see the run steps set the working directory in the debug logs:

```
##[debug]Evaluating condition for step: 'Run tests'
...
Run poetry run pytest --cov --cov-report xml:coverage.xml .
##[debug]Overwrite 'working-directory' base on job defaults.
```

Example yaml file:

```
jobs:
  test:
    defaults:
      run:
        working-directory: services/foo
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: poetry run pytest --cov --cov-report xml:coverage.xml .
      - name: Code coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: services/foo/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: .8
```
