### ISSUE TITLE
Why running only for pull requests events?

### ISSUE THREAD

**Issue by uilianries** [orgoro/coverage#280]
Hello and thank you for providing this project, it's really useful!

Currently I'm trying to use it for a project, but it seems like I can not decide about the logic involving the event due the follow condition:

https://github.com/orgoro/coverage/blob/c65003f41276ea33fe3a3a5d53df8b340462e8fa/src/index.ts#L14

```ts
const eventName = context.eventName
    if (eventName !== 'pull_request') {
      core.setFailed(`action support only pull requests but event is ${eventName}`)
      return
    }
```

So, basically we are only running nightly and manual `workflow_dispatch` CI jobs, which means, this project can not be used, because we still are not running for pull requests.

I would like to ask to raise that condition if possible, so users could decide the logic directly in their CI flow, instead:

```yaml
- name: Coverage report
  if: github.event_name == 'pull_request'
  uses: orgoro/coverage@v3.1
  with:
    coverageFile: xmlcov/coverage.xml
    token: ${{ secrets.GITHUB_TOKEN }}
```

Regards!
