### ISSUE TITLE
Fails At 100% Code Coverage

### ISSUE THREAD

**Issue by jvanderen1** [orgoro/coverage#286]
I tried setting my overall code coverage to 100%, but it never passes (even with 100% code coverage).

```yml
 - name: Display Coverage
    uses: orgoro/coverage@v3
    with:
      coverageFile: ./coverage.xml
      thresholdAll: 1.0
      token: ${{ secrets.GITHUB_TOKEN }}
```
