### ISSUE TITLE
Support changing the title to support posting coverage reports when running multiple versions of Python

### ISSUE THREAD

**Issue by RobertDeRose** [orgoro/coverage#320]
Like the title says, it would be nice if the title of the post could be updated to include the version of Python that the test were run against.  So if we use GitHub Workflows ability to run a matrix like so:

```yaml
jobs:
  tests:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
```

We could either have multiple comments, or since it appears the action already looks for an existing comment with the title "Python Coverage", that the table could be updated to include the report with the specific python version run with.

including a switch like `python-version:  ${{ matrix.python-version }}` would be nice for this
